/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.apontamentoleitor.services;

/**
 * Remote interface for ApontamentoLeitorSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ApontamentoLeitorSP
   extends javax.ejb.EJBObject
{

   public void apontarProducao( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

}
