/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.apontamentoleitor.services;

/**
 * Home interface for ApontamentoLeitorSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ApontamentoLeitorSPHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ApontamentoLeitorSP";
   public static final String JNDI_NAME="br/com/sankhya/apontamentoleitor/services/ApontamentoLeitorSP";

   public br.com.sankhya.apontamentoleitor.services.ApontamentoLeitorSP create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
